MYSQL_HOST="127.0.0.1"
MYSQL_PORT=3306
MYSQL_USER=isucon
MYSQL_DBNAME=isuumo
MYSQL_PASS=isucon

# chair テーブルは isu2 の MySQL でホストする (estate は isu1 のローカル MySQL のまま)
CHAIR_MYSQL_HOST=isu2
CHAIR_MYSQL_PORT=3306
CHAIR_MYSQL_USER=isucon
CHAIR_MYSQL_DBNAME=isuumo
CHAIR_MYSQL_PASS=isucon
